### ISSUE TITLE
Update your readme file

### ISSUE THREAD

**Issue by harsh-vish14** [Surajit10/Advance-Notepad#1]
can u update your read me file while reading i can't get what your project do

**Comment by Surajit10** [comment]
ok  Thanks

**Comment by harsh-vish14** [comment]
pls update that

**Comment by Surajit10** [comment]
What should i put?

**Comment by harsh-vish14** [comment]
small description of the project

**Comment by Surajit10** [comment]
Readme means it is description of my project?

**Comment by harsh-vish14** [comment]
yes
